version: '3'

services:
  search:
    build:
      context: ./search
      target: development
    entrypoint:
      - sleep
      - infinity
    depends_on:
      - queue
  queue:
    image: bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    restart: always
    healthcheck:
      test: test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 3s
      retries: 5
      start_period: 30s